### ISSUE TITLE
Selecting the number of players problem

### ISSUE THREAD

**Issue by xcx0902** [LocalGen-dev/LocalGen-new#11]
When I run in 800*450 and try to choose 3 players, but it shows that I chose the 7 one.

<img width="602" alt="image" src="https://user-images.githubusercontent.com/99001676/216748555-5aa7cc7c-b06c-4daa-ab05-dc69175dab76.png">

**Comment by chrhaa** [comment]
It's a bug by xrz.

**Comment by AppOfficer** [comment]
As the new UI is completed, the bug is fixed with the release of version 3.0.2.
