### ISSUE TITLE
Invalid macro name

### ISSUE THREAD

**Issue by Wan081018** [LocalGen-dev/LocalGen-new#16]
Maybe the macro names of the files contain invalid characters such as `-' in "LOCALGEN-NEW_PRIVATE_H".  
When i use the Dev-Cpp to compile it, it warns "extra tokens at the end of #ifndef".  
It means that it only checks if macro name "LOCALGEN" exists or not, but not "LOCALGEN-NEW_PRIVATE_H".  
The macro checking might be useless.

**Comment by AppOfficer** [comment]
It is a warning that we've noticed at the beginning of developping.
The warning doesn't affect the compiling, though.

**Comment by AppOfficer** [comment]
We've changed the dev name to LocalGen, so the problem is fixed.
