### ISSUE TITLE
Bot showing error in replay

### ISSUE THREAD

**Issue by xcx0902** [LocalGen-dev/LocalGen-new#23]
![image](https://user-images.githubusercontent.com/99001676/236428568-c9fa054d-c330-4971-9995-f592153a333f.png)

At the top right corner, it shows that all the players were played by "smartRandomBot". It is wrong as the red one must be "HUMAN".

**Comment by AppOfficer** [comment]
The bug is there because the replay files don't store bot name. The "Bot Name" column in replay ranklists is going to be deleted.

**Comment by AppOfficer** [comment]
The bug is fixed.
