### ISSUE TITLE
Font size too large on main page

### ISSUE THREAD

**Issue by CH3-CH2-ONa** [LocalGen-dev/LocalGen-new#26]
The application was run in full screen mode on a laptop with a display resolution of 2520 * 1680 and 150% DPI.   
<img width="1260" alt="untitled" src="https://github.com/LocalGen-dev/LocalGen-new/assets/139478204/63f68436-8096-4a30-b4e7-6da9d645a97e">

**Comment by AppOfficer** [comment]
That's definitely because you haven't install the fonts. Go to the fonts folder and download the fonts `Quicksand` and `Lucida Fax`.
